### PR TITLE
feat: make pytransform3d optional for simpler/smaller builds

### PR DESCRIPTION
**Pull request by LouisBrunner**
We are having a lot of issues with download `pytransform3d` on a lot of platforms due to its requirement of numpy, matplotlib, etc

Thus we will be checking if it's available and warn users to download it manually if they want it instead of packaging it ourselves. 

This is a breaking change.

### CODE REVIEW

**Comment by LouisBrunner** [comment]
This fixes #80

**Review by tallpress — APPROVED** [review]
LGTM. Small thing: maybe we could extract all `pytransform3d` stuff into it's own class so that we don't have to put the onus on developers to call `self.__ensure_pyt3d` before calling each function that requires `pytransform3d`

**Comment by LouisBrunner** [comment]
@tallpress I don't understand? A user of the SDK would never call that function (they can't, it's private anyway) but even if you make a class you still need to call the class?

**Comment by tallpress** [comment]
Reason being: the class can handle the checking if the lib exists (throw exception if not installed maybe?), but I guess caller would have to check for exceptions, so again maybe overkill for now. Would be more for devs developing the sdk rather than clients of the sdk

**Comment by LouisBrunner** [comment]
I am not sure I understand what would change/what we would gain

**Pull request merged**
