### PR TITLE
Feature/pypi changes

### PR DESCRIPTION
**Pull request by Charlesworth**
Update in line with publishing the package on Pypi, including:
 - adding the new `eva-sdk` package name
 - updating setup.py
 - add build artifact directories to .gitignore
 - add docs on versioning strategy for Pypi and document SDK - API version compatibility
 - add badge link to Pypi (this won't work until publish)

### CODE REVIEW

**Comment by LouisBrunner** [comment]
I am going through PEPs and I don't think `eva-sdk` is really idiomatic.
PEP8: https://www.python.org/dev/peps/pep-0008/#package-and-module-names
PEP423: https://www.python.org/dev/peps/pep-0423/#follow-pep-8-for-syntax-of-package-and-module-names

Maybe using a namespace, `automata.eva` would be better?

**Comment by Charlesworth** [comment]
@LouisBrunner yer we had a real naming conundrum last week on the Friday! We can't use "automata" or "eva" as they are already taken on pypi. We settled on some combination of "eva" and "sdk". Underscores aren't allowed so that left "evaSDK" and "eva-sdk". Looking at the names of the top 1000 packages and PEP suggestions, using "-" to separate seemed the most reasonable of the choices. We didn't consider name-spacing but also the PEP does state: "Don't plug into a namespace you don't own, unless explicitly authorized.", so I guess the options are choose another namespace i.e. "automata-tech" (which is free) or go for the "eva-sdk".

**Comment by LouisBrunner** [comment]
After looking at some of the package names, using dashes seem fine??

So either a non-existing namespace like `automatatech.eva` or `eva-sdk`, either is fine

**Comment by LouisBrunner** [comment]
As discussed offline, we will use `eva-sdk` for now and move to a namespace the day it's needed.

**Pull request merged**
